spring:
  devtools:
    add-properties: false
  sql:
    init:
      platform: psql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "$HEROKU_PSQL_URL"
    username: $PSQL_USERNAME
    password: $PSQL_PASS
security:
  jwt:
    secret: $JWT_SECRET