spring:
  devtools:
    add-properties: false
  sql:
    init:
      platform: psql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/techiesocialz"
    username: madalingiurca
    password: $PSQL_PASS
security:
  jwt:
    secret: $JWT_SECRET