server:
  port: 8087
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/techiez
    username: webadmin
    password: webadmin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
logging:
  level:
    web: debug
security:
  jwt:
    secret: my_very_secret_word_for_jwt_generation
