# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy workflow

on:
  push:
    branches:
      - mvp1

env:
  SCP_SOURCE_PATH: target/techieWorld-socialz-0.0.1-SNAPSHOT.jar
  JAR_FILE_NAME: techieWorld-socialz-0.0.1-SNAPSHOT
  APP_NAME: TechieWorld-Socialz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Replace database password
        uses: datamonsters/replace-action@v2
        with:
          files: 'src/main/resources/application.yaml'
          replacements: '$PSQL_PASS=${{ secrets.PSQL_PASSWORD }}'

      - name: Build with Maven
        run: mvn -B package --file pom.xml -P prod

      - name: Upload application
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: ${{ env.SCP_SOURCE_PATH }}
          target: "~/techieWorld-socialz-app/"
          strip_components: 1
          debug: true

      - name: Start Service
        uses: appleboy/ssh-action@master
        env:
          JAR_FILE_NAME: ${{ env.JAR_FILE_NAME }}
          APP_NAME: ${{ env.APP_NAME }}
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          debug: true
          envs: JAR_FILE_NAME,APP_NAME
          script: |
            sudo /etc/init.d/${APP_NAME} stop
            mv ~/techieWorld-socialz-app/${APP_NAME}.jar ~/techieWorld-socialz-app/${JAR_FILE_NAME}-old.jar
            mv ~/techieWorld-socialz-app/${JAR_FILE_NAME}.jar ~/techieWorld-socialz-app/${APP_NAME}.jar
            sudo rm -rf /etc/init.d/${APP_NAME}
            sudo ln -s -f ~/techieWorld-socialz-app/${APP_NAME}.jar /etc/init.d/${APP_NAME}
            sudo /etc/init.d/${APP_NAME} start
